source "http://rubygems.org"

gem "activerecord", "~> 3.1.1"
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem "mysql2"
gem 'em-synchrony', :git => 'git://github.com/igrigorik/em-synchrony.git',
                    :require => ['em-synchrony', 'em-synchrony/activerecord', 'em-synchrony/mysql2']
                            
gem 'grape'
gem 'goliath'
gem 'rack-oauth2-server'
gem 'oauth2'
gem 'songkick-oauth2-provider'
